# Generated by Django 2.2.6 on 2020-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=56, null=True)),
                ('Opportunity_ID', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=120)),
                ('opp_url', models.URLField(blank=True, help_text='copy and paste SFDC Opportunity URL', null=True)),
                ('lead_name', models.CharField(choices=[('Simon Woodford', 'Simon Woodford'), ('Vin Bolisetti', 'Vin Bolisetti')], max_length=56)),
                ('term_type', models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=120)),
                ('Leading_Product', models.CharField(choices=[('OpenText ContentSuite', 'OpenText ContentSuite'), ('OpenText Experience Suite', 'OpenText Experience Suite'), ('OpenText Process Suite', 'OpenText Process Suite'), ('OpenText Information Exchange Suite', 'OpenText Information Exchange Suite'), ('OpenText Discovery Suite', 'OpenText Discovery Suite'), ('OpenText Suite for SAP', 'OpenText Suite for SAP'), ('OpenText Suite for Oracle', 'OpenText Suite for Oracle'), ('OpenText Suite for Microsoft', 'OpenText Suite for Microsoft'), ('OpenText Appworks', 'OpenText Appworks'), ('OpenText Cloud', 'OpenText Cloud')], max_length=120)),
                ('penalties', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('managed_services', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('managed_services_rep', models.CharField(choices=[('M1', 'CDS Rep 1'), ('M2', 'CDS Rep 2'), ('M3', 'CDS Rep 3'), ('M4', 'CDS Rep 4'), ('M5', 'CDS Rep 5')], max_length=56, null=True)),
                ('local_Currency', models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF - Swiss Franc', 'CHF - Swiss Franc'), ('Euro - EURO', 'Euro - EURO'), ('GBP - British Pound', 'GBP - British Pound'), ('USD - US Dollar', 'USD - US Dollar'), ('RUB - Russian Ruble', 'RUB - Russian Ruble'), ('JPY - Japanese Yen', 'JPY - Japanese Yen')], max_length=56, null=True)),
            ],
        ),
    ]
