# Generated by Django 2.2.6 on 2020-05-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_name', models.CharField(max_length=56, null=True)),
                ('Opportunity_ID', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=120)),
                ('opp_url', models.URLField(blank=True, help_text='copy and paste SFDC Opportunity URL', null=True)),
                ('lead_name', models.CharField(choices=[('Simon Woodford', 'Simon Woodford'), ('Vin Bolisetti', 'Vin Bolisetti')], max_length=56)),
                ('term_type', models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=56)),
                ('Leading_Product', models.CharField(choices=[('OpenText ContentSuite', 'OpenText ContentSuite'), ('OpenText Experience Suite', 'OpenText Experience Suite'), ('OpenText Process Suite', 'OpenText Process Suite'), ('OpenText Information Exchange Suite', 'OpenText Information Exchange Suite'), ('OpenText Discovery Suite', 'OpenText Discovery Suite'), ('OpenText Suite for SAP', 'OpenText Suite for SAP'), ('OpenText Suite for Oracle', 'OpenText Suite for Oracle'), ('OpenText Suite for Microsoft', 'OpenText Suite for Microsoft'), ('OpenText Appworks', 'OpenText Appworks'), ('OpenText Cloud', 'OpenText Cloud')], max_length=120)),
                ('penalties', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=56)),
                ('managed_services', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=56, null=True)),
                ('managed_services_rep', models.CharField(choices=[('M1', 'CDS Rep 1'), ('M2', 'CDS Rep 2'), ('M3', 'CDS Rep 3'), ('M4', 'CDS Rep 4'), ('M5', 'CDS Rep 5')], max_length=56, null=True)),
                ('local_Currency', models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF', 'CHF - Swiss Franc'), ('EUR', 'Euro - EURO'), ('GBP', 'GBP - British Pound'), ('USD', 'USD - US Dollar'), ('RUB', 'RUB - Russian Ruble'), ('JPY', 'JPY - Japanese Yen')], max_length=56, null=True)),
                ('perpetualSoftwareOTDirectDiscount', models.IntegerField(default=10)),
                ('subscriptionSoftwareOTDirectDiscount', models.IntegerField(default=85)),
                ('perpetualSoftwareThirdPartyDiscount', models.IntegerField(default=5)),
                ('subscriptionSoftwareThirdPartyDiscount', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': 'Add Quotes',
            },
        ),
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod1Name', models.CharField(max_length=56)),
                ('mod1Num1', models.IntegerField()),
                ('mod1Num2', models.IntegerField()),
                ('mod1Bool1', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod2Name', models.CharField(max_length=56)),
                ('mod2Num1', models.IntegerField()),
                ('mod2Num2', models.IntegerField()),
                ('mod2Bool1', models.BooleanField()),
                ('commonName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TestModel1')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePerpetualModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleName', models.CharField(max_length=128)),
                ('scheduleURL', models.URLField()),
                ('add_quote_sched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.AddQuote')),
            ],
        ),
        migrations.CreateModel(
            name='AddSubscriptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('thirdPartyContent', models.CharField(choices=[('No', 'No third party'), ('100%', '100% third party')], max_length=56)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=128)),
                ('salesDisc', models.IntegerField()),
                ('currency', models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF', 'CHF - Swiss Franc'), ('EUR', 'Euro - EURO'), ('GBP', 'GBP - British Pound'), ('USD', 'USD - US Dollar'), ('RUB', 'RUB - Russian Ruble'), ('JPY', 'JPY - Japanese Yen')], max_length=56)),
                ('netSales', models.DecimalField(decimal_places=2, max_digits=13)),
                ('mcv', models.FloatField(max_length=128)),
                ('volDiscPrice', models.DecimalField(decimal_places=2, max_digits=13)),
                ('termYearly', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('productType', models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=128)),
                ('OppId', models.CharField(max_length=26)),
                ('thirdPartyBool', models.BooleanField(default=None, max_length=6)),
                ('validProductType', models.BooleanField(default=False)),
                ('ePerpFactor', models.IntegerField(default=49)),
                ('add_quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.AddQuote')),
            ],
        ),
        migrations.CreateModel(
            name='AddPerpetualModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName_p', models.CharField(max_length=128)),
                ('thirdPartyContent_p', models.CharField(choices=[('No', 'No third party'), ('100%', '100% third party')], max_length=56)),
                ('quantity_p', models.IntegerField()),
                ('units_p', models.CharField(max_length=128)),
                ('salesDisc_p', models.IntegerField()),
                ('currency_p', models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF', 'CHF - Swiss Franc'), ('EUR', 'Euro - EURO'), ('GBP', 'GBP - British Pound'), ('USD', 'USD - US Dollar'), ('RUB', 'RUB - Russian Ruble'), ('JPY', 'JPY - Japanese Yen')], max_length=56)),
                ('netSales_p', models.DecimalField(decimal_places=2, max_digits=13)),
                ('mcv_p', models.FloatField(max_length=128)),
                ('volDiscPrice_p', models.FloatField(max_length=13)),
                ('termMonthly_p', models.IntegerField()),
                ('productType_p', models.CharField(choices=[('License', 'License'), ('Support', 'Support')], max_length=56)),
                ('OppId_p', models.CharField(max_length=26)),
                ('add_quote_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.AddQuote')),
                ('add_quote_sched_perp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SchedulePerpetualModel')),
            ],
        ),
    ]
