# Generated by Django 2.2.6 on 2020-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubscriptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=128)),
                ('thirdPartyContent', models.CharField(choices=[('No', 'No third party'), ('100%', '100% third party')], max_length=4)),
                ('quantity', models.IntegerField(max_length=4)),
                ('units', models.CharField(max_length=128)),
                ('salesDisc', models.IntegerField(max_length=3)),
                ('currency', models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF', 'CHF - Swiss Franc'), ('EUR', 'Euro - EURO'), ('GBP', 'GBP - British Pound'), ('USD', 'USD - US Dollar'), ('RUB', 'RUB - Russian Ruble'), ('JPY', 'JPY - Japanese Yen')], max_length=3)),
                ('netSales', models.FloatField(max_length=128)),
                ('mcv', models.FloatField(max_length=128)),
                ('volDiscPrice', models.FloatField(max_length=128)),
                ('termYearly', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('productType', models.CharField(choices=[('CS', 'Cloud Subscription'), ('CP', 'Cloud Perpetual'), ('SS', 'SaaS')], max_length=2)),
                ('OppId', models.CharField(max_length=26)),
                ('validProductType', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='addquote',
            options={'verbose_name_plural': 'Add Quotes'},
        ),
        migrations.AlterField(
            model_name='addquote',
            name='local_Currency',
            field=models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('CHF', 'CHF - Swiss Franc'), ('EUR', 'Euro - EURO'), ('GBP', 'GBP - British Pound'), ('USD', 'USD - US Dollar'), ('RUB', 'RUB - Russian Ruble'), ('JPY', 'JPY - Japanese Yen')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='managed_services_rep',
            field=models.CharField(choices=[('M1', 'CDS Rep 1'), ('M2', 'CDS Rep 2'), ('M3', 'CDS Rep 3'), ('M4', 'CDS Rep 4'), ('M5', 'CDS Rep 5')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='term_type',
            field=models.CharField(choices=[('CS', 'Cloud Subscription'), ('CP', 'Cloud Perpetual'), ('SS', 'SaaS')], max_length=2),
        ),
    ]
